name: slurm
version: '0.1' 
summary: Slurm Workload Manager
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster management and
  job scheduling system for large and small Linux clusters.

grade: stable
confinement: strict

base: core18


apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
    plugs:
        - avahi-observe # network discovery
        - hardware-observe
        - kernel-module-observe
        - mount-observe
        - network
        - network-bind
        - network-observe
        - network-control
        - system-observe

  supervisorctl:
    command: bin/run-supervisorctl
    plugs:
        - avahi-observe # network discovery
        - network
        - network-bind
        - network-observe
        - network-control
        - system-observe

  munged:
    daemon: simple
    command: bin/munged
    plugs:
      - network
      - network-bind
  munge:
    command: bin/munge
  unmunge:
    command: bin/unmunge
  remunged:
    command: bin/remunge
  mungekey:
    command: bin/mungekey


parts:
  supervisord:
    plugin: dump
    source: src/supervisord/
    source-type: local
    build-packages:
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3-pip
      - python3-setuptools
    override-pull: |
      snapcraftctl pull
      pip3 install jinja2 supervisor pyaml

  munge:
    plugin: dump
    source: https://github.com/dun/munge.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-packages:
      - gcc
      - libssl-dev
      - autoconf
      - make
      - libtool
      - zlib1g-dev
      - libbz2-dev
    stage:
      - usr/
      - var/
      - etc/
    prime:
      - usr/
      - etc/
      - var/
    override-build: |
      snapcraftctl build
      ./bootstrap
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr \
          --sysconfdir=$SNAPCRAFT_PART_INSTALL/etc \
          --localstatedir=$SNAPCRAFT_PART_INSTALL/var \
          --libdir=$SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu
      make
      make install

  munge-customizations:
    plugin: dump
    source: src/munge/

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/

  boost:
    plugin: dump
    source: https://github.com/kyrofa/boost_tarball/raw/master/boost_1_59_0.tar.gz
    source-checksum: sha1/5123209db194d66d69a9cfa5af8ff473d5941d97
    # When building MySQL, the headers in the source directory 'boost/' are
    # required. Previously, using the 'copy' plugin, the whole archive was put
    # under 'boost/', making the headers reside in 'boost/boost/'. Due to a bug,
    # we now only stage the 'boost/' directory without moving it.
    #
    # Bug: https://bugs.launchpad.net/snapcraft/+bug/1757093
    stage:
      - boost/
    prime:
      - -*

  mysql:
    plugin: cmake
    source: https://github.com/mysql/mysql-server.git
    source-tag: mysql-5.7.28
    source-depth: 1
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/mysql-support-compile-time-disabling-of-setpriority.patch
    after: [boost, patches]
    configflags:
      - -DWITH_BOOST=$SNAPCRAFT_STAGE
      - -DWITH_INNODB_PAGE_CLEANER_PRIORITY=OFF
      - -DCMAKE_INSTALL_PREFIX=/
      - -DBUILD_CONFIG=mysql_release
      - -DWITH_UNIT_TESTS=OFF
      - -DWITH_EMBEDDED_SERVER=OFF
      - -DWITH_ARCHIVE_STORAGE_ENGINE=OFF
      - -DWITH_BLACKHOLE_STORAGE_ENGINE=OFF
      - -DWITH_FEDERATED_STORAGE_ENGINE=OFF
      - -DWITH_PARTITION_STORAGE_ENGINE=OFF
      - -DINSTALL_MYSQLTESTDIR=
    build-packages:
      - wget
      - g++
      - cmake
      - bison
      - libncurses5-dev
      - libaio-dev
      - libssl-dev
      - pkg-config
    stage-packages:
      - libaio1
    stage:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server
      - -COPYING
    prime:
      # Remove scripts that we'll be replacing with our own
      - -support-files/mysql.server

      # Remove unused binaries that waste space
      - -bin/innochecksum
      - -bin/lz4_decompress
      - -bin/myisam*
      - -bin/mysqladmin
      - -bin/mysqlbinlog
      - -bin/mysql_client_test
      - -bin/mysql_config*
      - -bin/mysqld_multi
      - -bin/mysqlimport
      - -bin/mysql_install_db
      - -bin/mysql_plugin
      - -bin/mysqlpump
      - -bin/mysql_secure_installation
      - -bin/mysqlshow
      - -bin/mysqlslap
      - -bin/mysql_ssl_rsa_setup
      - -bin/mysqltest
      - -bin/mysql_tzinfo_to_sql
      - -bin/perror
      - -bin/replace
      - -bin/resolveip
      - -bin/resolve_stack_dump
      - -bin/zlib_decompress

  # Copy over our MySQL scripts
  mysql-customizations:
    plugin: dump
    source: src/mysql/

  patches:
    source: src/patches
    plugin: dump
    prime:
      - -*

  common:
    plugin: dump
    source: src/common/
    source-type: local

  slurm:
    after:
      - json-c
      - libcurl
      - glib
      - munge
    plugin: dump
    source: https://download.schedmd.com/slurm/slurm-20.02.0.tar.bz2
    build-packages:
      - libhdf5-dev
      - python-dev
      - libreadline-dev
      - liblua5.3-dev
      - libbz2-dev
      - bzip2
      - mysql-client
      - libmysqlclient-dev
      - liblz4-dev
      - libpmi1-pmix
      - freeipmi
      - rrdtool
      - libncurses5-dev
    stage-packages:
      - liblua5.3-dev
      - libmysqlclient-dev
      - libaec0
      - libhdf5-100
      - libsz2
      - mailutils
    stage:
      - bin/
      - share/
      - sbin/
      - include/
      - lib/
      - etc/
      - usr/
    prime:
      - bin/
      - share/
      - sbin/
      - include/
      - lib/
      - etc/
      - usr/
    override-build: |
      snapcraftctl build
      #LD_LIBRARY_PATH=$SNAPCRAFT_STAGE/lib:$SNAPCRAFT_STAGE/opt:$SNAPCRAFT_STAGE \
      ./configure --enable-threading \
          --with-munge=$SNAPCRAFT_STAGE/usr/lib/x86_64-linux-gnu \
          --with-json=$SNAPCRAFT_STAGE \
          --with-libcurl=$SNAPCRAFT_STAGE/opt/curl \
          --prefix=$SNAPCRAFT_PART_INSTALL \
          --localstatedir=/var/snap/slurm/common/etc/slurm
      make -j9
      make install
      ldconfig -n /snap/slurm/current/lib/slurm/

  glib:
    plugin: dump
    source: https://github.com/GNOME/glib.git
    source-type: git
    source-depth: 1
    source-tag: 2.62.2
    build-packages:
      - pkg-config
      - libmount-dev
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build
    stage:
      - -README
    prime:
      - -*
    override-build: |
      snapcraftctl build
      pip3 install meson
      meson _build
      ninja -C _build
      ninja -C _build install

  json-c:
    plugin: cmake
    configflags:
      - "-DBUILD_SHARED_LIBS=On"
    source: https://github.com/json-c/json-c.git
    source-type: git
    source-depth: 1
    source-tag: json-c-0.13.1-20180305
    build-packages:
      - g++
      - libtool
    stage:
      - include/
    prime:
      - -*

  libcurl:
    plugin: dump
    source: https://github.com/curl/curl.git
    source-type: git
    source-depth: 1
    source-tag: curl-7_62_0
    build-packages:
      - libtool
      - libssl-dev
      - autoconf
      - make
    stage:
      - opt/
    prime:
      - -*
    override-build: |
      snapcraftctl build
      ./buildconf
      ./configure --with-ssl --prefix=$SNAPCRAFT_PART_INSTALL/opt/curl/
      make -j9
      make install

  slurm-configurator:
    plugin: dump
    source: src/slurm-configurator/
    source-type: local

  slurm-bins:
    plugin: dump
    source: src/slurm-bins/
    source-type: local
