name: slurm
version: '0.1' 
summary: Slurm Workload Manager
description: |
  Slurm is an open source, fault-tolerant, and highly scalable cluster management and
  job scheduling system for large and small Linux clusters.

grade: stable
confinement: strict

base: core18


apps:
  supervisor:
    daemon: simple
    command: bin/run-supervisord
    plugs:
        - avahi-observe # network discovery
        - hardware-observe
        - kernel-module-observe
        - mount-observe
        - network
        - network-bind
        - network-observe
        - network-control
        - system-observe

  munged:
    daemon: simple
    command: bin/munged
    plugs:
      - network
      - network-bind
  munge:
    command: bin/munge
  unmunge:
    command: bin/unmunge
  remunged:
    command: bin/remunge
  mungekey:
    command: bin/mungekey


parts:
  supervisord:
    plugin: dump
    source: src/supervisord/
    source-type: local
    build-packages:
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3-pip
      - python3-setuptools
    override-pull: |
      snapcraftctl pull
      pip3 install jinja2 supervisor

  munge:
    plugin: dump
    source: https://github.com/dun/munge.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-packages:
      - gcc
      - libssl-dev
      - autoconf
      - make
      - libtool
      - zlib1g-dev
      - libbz2-dev
    stage:
      - usr/
      - var/
      - etc/
    prime:
      - usr/
      - etc/
      - var/
    override-build: |
      snapcraftctl build
      ./bootstrap
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr \
          --sysconfdir=$SNAPCRAFT_PART_INSTALL/etc \
          --localstatedir=$SNAPCRAFT_PART_INSTALL/var \
          --libdir=$SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu
      make
      make install

  munge-customizations:
    plugin: dump
    source: src/munge/

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/
